---
- name: Install APT packages
  apt:
    name: "{{ item }}"
  become: yes
  become_method: sudo
  with_items:
    - libreoffice
    - dia
    - kcalc
    - okular
    - acroread
    - poppler-utils # for pdfunite
    - kontact
    - kalarm

- name: Add APT key for Canon scan software
  apt_key:
    url: http://keyserver.ubuntu.com:11371/pks/lookup?op=get&search=0x84E550CD36EC35430A66AC5A03396E1C3F7B4A1D
  become: yes
  become_method: sudo
  tags: legacy

- name: Add APT source for Canon scan software
  apt_repository:
    repo: deb http://ppa.launchpad.net/michael-gruz/canon-trunk/ubuntu precise main
  become: yes
  become_method: sudo
  tags: legacy

- name: Install APT packages for Canon scan software
  apt:
    name: "{{ item }}"
  become: yes
  become_method: sudo
  with_items:
    - scangearmp-common
    - scangearmp-mg2100series
    - scangearmp-mg2200series
  tags: legacy
