---
- name: Install APT packages
  apt:
    name: "{{ item }}"
  become: yes
  become_method: sudo
  with_items:
    - vlc
    - transcode
    - kolourpaint4
    - gwenview
    - imagemagick
    - gimp
    - calibre
    - audacity
    - k3b
