---
- name: Add APT key for git
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: E1DD270288B4E6030699E45FA1715D88E1DF1F24
  become: yes
  become_method: sudo

- name: Add APT source for git
  apt_repository:
    repo: deb http://ppa.launchpad.net/git-core/ppa/ubuntu precise main
  become: yes
  become_method: sudo

- name: Install git
  apt:
    name: "{{ item }}"
    state: latest
  become: yes
  become_method: sudo
  with_items:
    - git
    - git-man
    - git-gui
    - gitk
