---
- name: Install git
  apt:
    deb: "{{ item }}"
  become: yes
  become_method: sudo
  with_items:
    # git 2.7 breaks the "email = (none)" feature. See ongoing discussion at
    # http://www.spinics.net/lists/git/msg267338.html
    - "{{ role_path }}/files/git_2.4.6-0ppa1-ubuntu14.10.1_amd64.deb"
    - "{{ role_path }}/files/git-man_2.4.6-0ppa1-ubuntu14.10.1_all.deb"
    - "{{ role_path }}/files/git-gui_2.4.6-0ppa1-ubuntu14.10.1_all.deb"
    - "{{ role_path }}/files/gitk_2.4.6-0ppa1-ubuntu14.10.1_all.deb"
