---
- hosts: all
  roles:
    - apt-client
    - home-tracker
    - desktop-env
    - dev-toolbox
    - { role: windows-emulator, when: is_windows_emulator }
    - { role: office-toolbox, when: is_office_toolbox }
    - { role: multimedia-toolbox, when: is_multimedia_toolbox }
    - { role: com-toolbox, when: is_com_toolbox }
    - { role: web-browser, when: is_web_browser }
    - { role: laptop, when: is_laptop }
    - extra
  tasks:
    - name: "bad: has_spotify and !is_multimedia_toolbox"
      fail:
        msg: Inconsistent variables
      when: has_spotify and is_multimedia_toolbox == False
    - name: "bad: has_deluge and !is_multimedia_toolbox"
      fail:
        msg: Inconsistent variables
      when: has_deluge and is_multimedia_toolbox == False
    - name: "bad: has_grive and !is_office_toolbox"
      fail:
        msg: Inconsistent variables
      when: has_grive and is_office_toolbox == False
    - name: "bad: npm_is_from_apt and !has_npm"
      fail:
        msg: Inconsistent variables
      when: npm_is_from_apt and has_npm == False
