---
- hosts: all
  roles:
    - apt-client
    - home-tracker
    - desktop-env
    - dev-toolbox
    - windows-emulator
    - office-toolbox
    - multimedia-toolbox
    - com-toolbox
    - web-browser
    - laptop
    - extra
