---
- name: Install lubuntu-desktop via APT
  apt:
    name: lubuntu-desktop
  become: yes
  become_method: sudo
  when: has_lubuntu_desktop

- name: Install other APT packages
  apt:
    name: "{{ item }}"
  become: yes
  become_method: sudo
  with_items:
    - gnome-control-center
    - network-manager-gnome
    - xscreensaver
    - devilspie
    - xdotool
    - wmctrl
  when: has_lubuntu_desktop

- name: Deploy gnome-terminal configuration
  copy:
    src: "{{ inventory_dir }}/files/gnome-terminal"
    dest: "{{ lookup('env', 'HOME') }}/.gconf/apps"
  when: has_lubuntu_desktop
  tags: legacy
