---
#FIXME: this is a workaround because Ansible's APT module is way too slow on an initial rollout.
- name: Install lubuntu-desktop via APT
  # Without 'noninteractive', lightdm's installation hangs on "Preconfiguring packages ...":
  shell: DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends --no-upgrade lubuntu-desktop | ts '%F %T' >> ansible_apt.log
  become: yes
  become_method: sudo

- name: Install Lua for devilspie2
  apt:
    name: lua5.2
  become: yes
  become_method: sudo
  tags: legacy

- name: Install recent devilspie2
  apt:
    deb: "{{ role_path }}/files/devilspie2_0.39-4_amd64.deb"
  become: yes
  become_method: sudo
  tags: legacy

- name: Install other APT packages
  apt:
    name: "{{ item }}"
  become: yes
  become_method: sudo
  with_items:
    - gnome-control-center
    - network-manager-gnome
    - xscreensaver
    - wmctrl

- name: Install xdotool's dependencies
  apt:
    name: "{{ item }}"
  become: yes
  become_method: sudo
  with_items:
    - libxtst-dev
    - libxinerama-dev
    - libxkbcommon-dev

- name: Install xdotool
  command: make install
  args:
    chdir: "{{ role_path }}/files/xdotool-2d7c391"
  become: yes
  become_method: sudo

- name: Deploy setxkb
  template:
    src: "{{ role_path }}/files/setxkb.sh"
    dest: "{{ lookup('env', 'HOME') }}/bin/setxkb.sh"
    mode: 0775

- name: Deploy gnome-terminal configuration
  copy:
    src: "{{ inventory_dir }}/files/gnome-terminal"
    dest: "{{ lookup('env', 'HOME') }}/.gconf/apps"
  tags: legacy
