---
- name: Install other APT packages
  apt:
    name: "{{ item }}"
  become: yes
  become_method: sudo
  with_items:
    - gnome-control-center
    - network-manager-gnome
    - network-manager-openvpn-gnome
    - arandr

- name: Install xdotool's dependencies
  apt:
    name: "{{ item }}"
  become: yes
  become_method: sudo
  with_items:
    - libxtst-dev
    - libxinerama-dev
    - libxkbcommon-dev
    - make
    - gcc

- name: Build xdotool
  command: make
  args:
    chdir: "{{ role_path }}/files/xdotool"

- name: Install xdotool
  command: make install
  args:
    chdir: "{{ role_path }}/files/xdotool"
  become: yes
  become_method: sudo

- name: Deploy setxkb
  template:
    src: "{{ role_path }}/files/setxkb.sh"
    dest: "{{ lookup('env', 'HOME') }}/bin/setxkb.sh"
    mode: 0775

- name: Install cryptsetup for mount_encrypted_sdcard.sh
  apt:
    name: cryptsetup
  become: yes
  become_method: sudo
