---
#FIXME: this is a workaround because Ansible's APT module is way too slow on an initial rollout.
- name: Install lubuntu-desktop via APT
  shell: "apt-get install -y --no-install-recommends --no-upgrade {{ item }} | ts '%F %T' >> ansible_apt.log"
  become: yes
  become_method: sudo
  with_items:
    #FIXME: as a workaround, we pre-install a couple of lubuntu-desktop deps because the chromebook
    #       ASUS C200 doesn't have enough resources to install all at once on an initial rollout.
    - xfce4-power-manager
    - mplayer2
    - wpasupplicant
    - printer-driver-pnm2ppa
    - openprinting-ppds
    - lubuntu-core
    - language-selector-gnome
    - abiword
    - audacious
    - evince
    - gnome-mplayer
    - xfburn
    - usb-creator-gtk
    - transmission-gtk
    - pidgin
    - blueman
    - cups
    - system-config-printer-gnome
    - lubuntu-desktop
  when: has_lubuntu_desktop

- name: Install Lua for devilspie2
  apt:
    name: lua5.2
  become: yes
  become_method: sudo
  when: has_lubuntu_desktop
  tags: legacy

- name: Install recent devilspie2
  apt:
    deb: "{{ role_path }}/files/devilspie2_0.39-4_amd64.deb"
  become: yes
  become_method: sudo
  when: has_lubuntu_desktop
  tags: legacy

- name: Install other APT packages
  apt:
    name: "{{ item }}"
  become: yes
  become_method: sudo
  with_items:
    - gnome-control-center
    - network-manager-gnome
    - xscreensaver
    - xdotool
    - wmctrl
  when: has_lubuntu_desktop

- name: Deploy gnome-terminal configuration
  copy:
    src: "{{ inventory_dir }}/files/gnome-terminal"
    dest: "{{ lookup('env', 'HOME') }}/.gconf/apps"
  when: has_lubuntu_desktop
  tags: legacy

- name: Cleanup older start_icon location
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ lookup('env', 'HOME') }}/.local/share/configurelinux/start_icon.png"
    - "{{ lookup('env', 'HOME') }}/.local/share/configurelinux/start_icon.png.old"
