---
- name: Install lubuntu-gtk-core
  apt:
    name: lubuntu-gtk-core
  become: yes
  become_method: sudo
  ignore_errors: yes # Not available on Ubuntu 14.04

#FIXME: this is a workaround because Ansible's APT module is way too slow on an initial rollout.
- name: Install lubuntu-desktop via APT
  # Without 'noninteractive', lightdm's installation hangs on "Preconfiguring packages ...":
  shell: DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends --no-upgrade lubuntu-desktop | ts '%F %T' >> ansible_apt.log
  become: yes
  become_method: sudo

- name: Install xscreensaver
  apt:
    name: xscreensaver
  become: yes
  become_method: sudo

- name: Remove gnome-screensaver
  apt:
    name: gnome-screensaver
    state: absent
  become: yes
  become_method: sudo

- name: Install other APT packages
  apt:
    name: "{{ item }}"
  become: yes
  become_method: sudo
  with_items:
    - gnome-control-center
    - network-manager-gnome
    - network-manager-openvpn-gnome

- name: Install xdotool's dependencies
  apt:
    name: "{{ item }}"
  become: yes
  become_method: sudo
  with_items:
    - libxtst-dev
    - libxinerama-dev
    - libxkbcommon-dev

- name: Build xdotool
  command: make
  args:
    chdir: "{{ role_path }}/files/xdotool"

- name: Install xdotool
  command: make install
  args:
    chdir: "{{ role_path }}/files/xdotool"
  become: yes
  become_method: sudo

- name: Deploy setxkb
  template:
    src: "{{ role_path }}/files/setxkb.sh"
    dest: "{{ lookup('env', 'HOME') }}/bin/setxkb.sh"
    mode: 0775

- name: Install cryptsetup for mount_encrypted_sdcard.sh
  apt:
    name: cryptsetup
  become: yes
  become_method: sudo
