---
- name: Install emacs via APT
  apt:
    name: emacs
  become: yes
  become_method: sudo

- name: Install other text editors via APT
  apt:
    name: "{{ item }}"
  become: yes
  become_method: sudo
  with_items:
    - kwrite
    - gedit

- name: Install coding tools via APT
  apt:
    name: "{{ item }}"
  become: yes
  become_method: sudo
  with_items:
    - kompare
    - kdiff3
    - pandoc

- name: Install SCM clients via APT
  apt:
    name: "{{ item }}"
  become: yes
  become_method: sudo
  with_items:
    - mercurial
    - subversion
    - bzr

- name: Install interpreters via APT
  apt:
    name: "{{ item }}"
  become: yes
  become_method: sudo
  with_items:
    - rhino
    - groovy
    - ruby-all-dev

- name: Install python via APT
  apt:
    name: "{{ item }}"
  become: yes
  become_method: sudo
  with_items:
    - python-dev
    - python-testresources # for python-openstackclient

- name: Install python linters via APT
  apt:
    name: "{{ item }}"
  become: yes
  become_method: sudo
  with_items:
    - pychecker
    - pylint
    - pyflakes

#FIXME: this is a workaround because Ansible's APT module is way too slow on an initial rollout.
- name: Install LaTeX stuff via APT
  shell: apt-get install -y --no-install-recommends --no-upgrade texlive-latex-base texlive-latex-extra pgf | ts '%F %T' >> ansible_apt.log
  become: yes
  become_method: sudo

- name: Install FTP client via APT
  apt:
    name: gftp
  become: yes
  become_method: sudo

- name: Install MySQL client via APT
  apt:
    name: mysql-client
  become: yes
  become_method: sudo

- name: Install other network clients via APT
  apt:
    name: "{{ item }}"
  become: yes
  become_method: sudo
  with_items:
    - telnet
    - sshpass
    - mtr
    - dnsutils # for dig
    - tftp

- name: Install gnome-terminal via APT
  apt:
    name: gnome-terminal
  become: yes
  become_method: sudo

- name: Install shell tools via APT
  apt:
    name: "{{ item }}"
    force: yes #FIXME shouldn't be necessary, needed because "mc-data mc cannot be authenticated"
  become: yes
  become_method: sudo
  with_items:
    - trash-cli
    - mc
    - pv
    - bash-completion
    - lib32ncurses5
    - pdfgrep
    - tmux
    - clusterssh
    - w3m
    - rsync

- name: Install other system tools via APT
  apt:
    name: "{{ item }}"
  become: yes
  become_method: sudo
  with_items:
    - apt-file
    - locate
    - lsof
    - htop
    - ethtool

#FIXME: this is a workaround because Ansible's APT module is way too slow on an initial rollout.
- name: Install maven stuff via APT
  shell: apt-get install -y --no-install-recommends --no-upgrade maven2 | ts '%F %T' >> ansible_apt.log
  become: yes
  become_method: sudo

- name: Install MongoDB via APT
  apt:
    name: mongodb
  become: yes
  become_method: sudo

- name: Install gmrun via APT
  apt:
    name: gmrun
  become: yes
  become_method: sudo

- name: Install other APT packages
  apt:
    name: "{{ item }}"
  become: yes
  become_method: sudo
  with_items:
    - mcrypt
    - pwgen
    - xbacklight # for IntelliJ IDEA
    - seahorse # for generating OpenPGP keys

- name: Install pip
  apt:
    name: python-pip
  become: yes
  become_method: sudo

- name: Install uncommitted
  pip:
    name: uncommitted
  become: yes
  become_method: sudo

- name: "Add source line to bashrc"
  lineinfile:
    dest: "{{ main_bashrc_on_host }}"
    line: "source ${ansibleInventoryDir}/files/bashrc # uuidgen-79cb621e-49f4-4662-bd6c-518e97ae97cb"
    regexp: uuidgen-79cb621e-49f4-4662-bd6c-518e97ae97cb
    insertafter: uuidgen-20ce84f6-6313-4d61-8641-245c42741ffb

#FIXME: this task is executed each time:
# Note: you can list gedit settings with `gsettings list-recursively | grep -i gedit`.
- name: Configure gedit
  command: "gsettings set {{ item }}"
  with_items:
    - org.gnome.gedit.preferences.editor create-backup-copy false
    - org.gnome.gedit.preferences.editor display-line-numbers true
