---
- name: Install text editors via APT
  apt:
    name: "{{ item }}"
  become: yes
  become_method: sudo
  with_items:
    - kwrite
    - gedit

- name: Install coding tools via APT
  apt:
    name: "{{ item }}"
  become: yes
  become_method: sudo
  with_items:
    - kompare
    - kdiff3
    - pandoc
    - okteta

- name: Install SCM clients via APT
  apt:
    name: "{{ item }}"
  become: yes
  become_method: sudo
  with_items:
    - mercurial
    - subversion
    - bzr

- name: Install interpreters via APT
  apt:
    name: "{{ item }}"
  become: yes
  become_method: sudo
  with_items:
    - rhino
    - groovy
    - node-typescript # for tsc
    - ruby-all-dev
    - php-cli
    - php-xml # for https://github.com/WordPress/WordPress-Coding-Standards
    - php-imagick

- name: Install dependency managers via APT
  apt:
    name: "{{ item }}"
  become: yes
  become_method: sudo
  with_items:
    - composer
    - python3-pip

- name: Install python via APT
  apt:
    name: "{{ item }}"
  become: yes
  become_method: sudo
  with_items:
    - python3-dev
    - python3.8-dev
    - ipython3

- name: Install python linters via APT
  apt:
    name: "{{ item }}"
  become: yes
  become_method: sudo
  with_items:
    - pylint
    - pyflakes3

- name: Install tools to contribute to Ubuntu
  apt:
    name: "{{ item }}"
  become: yes
  become_method: sudo
  with_items:
    - devscripts # for rmadison
    - ubuntu-dev-tools # for pull-lp-source
    - cloud-image-utils # https://serverfault.com/a/940686/212098
    - git-buildpackage

#FIXME: this is a workaround because Ansible's APT module is way too slow on an initial rollout.
- name: Install LaTeX stuff via APT
  shell: apt-get install -y --no-install-recommends --no-upgrade texlive-latex-base texlive-latex-extra pgf | ts '%F %T' >> ansible_apt.log
  become: yes
  become_method: sudo

- name: Install MySQL client via APT
  apt:
    name: mysql-client
  become: yes
  become_method: sudo

- name: Install other networking tools via APT
  apt:
    name: "{{ item }}"
  become: yes
  become_method: sudo
  with_items:
    - telnet
    - sshpass
    - sshuttle
    - mtr
    - dnsutils # for dig
    - gftp
    - tftp
    - net-tools # for ifconfig

- name: Install gnome-terminal via APT
  apt:
    name: gnome-terminal
  become: yes
  become_method: sudo

- name: Install shell tools via APT
  apt:
    name: "{{ item }}"
    force: yes #FIXME shouldn't be necessary, needed because "mc-data mc cannot be authenticated"
  become: yes
  become_method: sudo
  with_items:
    - trash-cli
    - mc
    - ncdu
    - pv
    - bash-completion
    - lib32ncurses6
    - pdfgrep
    - byobu
    - clusterssh
    - w3m
    - rsync
    - curl
    - xmlstarlet
    - gcp

- name: Install other system tools via APT
  apt:
    name: "{{ item }}"
  become: yes
  become_method: sudo
  with_items:
    - apt-file
    - locate
    - lsof
    - htop
    - ethtool
    - gparted
    - partitionmanager

#FIXME: this is a workaround because Ansible's APT module is way too slow on an initial rollout.
- name: Install maven stuff via APT
  shell: apt-get install -y --no-install-recommends --no-upgrade maven2 | ts '%F %T' >> ansible_apt.log
  become: yes
  become_method: sudo

- name: Install gmrun via APT
  apt:
    name: gmrun
  become: yes
  become_method: sudo

- name: Install other APT packages
  apt:
    name: "{{ item }}"
  become: yes
  become_method: sudo
  with_items:
    - mcrypt
    - pwgen
    - xbacklight # for IntelliJ IDEA
    - seahorse # for generating OpenPGP keys
    # See https://wiki.ubuntuusers.de/ExifTool/
    - libimage-exiftool-perl
    - perl-doc

- name: Install uncommitted
  pip:
    name: uncommitted
  become: yes
  become_method: sudo

- name: Install black
  pip:
    name: black
  become: yes
  become_method: sudo

- name: "Add source line to bashrc"
  lineinfile:
    dest: "{{ main_bashrc_on_host }}"
    line: "source ${ansibleInventoryDir}/files/bashrc # uuidgen-79cb621e-49f4-4662-bd6c-518e97ae97cb"
    regexp: uuidgen-79cb621e-49f4-4662-bd6c-518e97ae97cb
    insertafter: uuidgen-20ce84f6-6313-4d61-8641-245c42741ffb

#FIXME: this task is executed each time:
# Note: you can list gedit settings with `gsettings list-recursively | grep -i gedit`.
- name: Configure gedit
  command: "gsettings set {{ item }}"
  with_items:
    - org.gnome.gedit.preferences.editor create-backup-copy false
    - org.gnome.gedit.preferences.editor display-line-numbers true
