---
- name: Install text editors via APT
  apt:
    name: "{{ item }}"
  become: yes
  become_method: sudo
  with_items:
    - kwrite
    - emacs
    - gedit

- name: Install coding tools via APT
  apt:
    name: "{{ item }}"
  become: yes
  become_method: sudo
  with_items:
    - kompare
    - kdiff3
    - pandoc

- name: Install SCM clients via APT
  apt:
    name: "{{ item }}"
  become: yes
  become_method: sudo
  with_items:
    - mercurial
    - subversion

- name: Install interpreters via APT
  apt:
    name: "{{ item }}"
  become: yes
  become_method: sudo
  with_items:
    - rhino
    - groovy

- name: Install python stuff via APT
  apt:
    name: "{{ item }}"
  become: yes
  become_method: sudo
  with_items:
    - python-dev
    - pychecker
    - pylint

- name: Install LaTeX stuff via APT
  apt:
    name: "{{ item }}"
  become: yes
  become_method: sudo
  with_items:
    - texlive-latex-base
    - texlive-latex-extra
    - pgf

- name: Install network clients via APT
  apt:
    name: "{{ item }}"
  become: yes
  become_method: sudo
  with_items:
    - gftp
    - telnet
    - sshpass
    - mtr

- name: Install shell tools via APT
  apt:
    name: "{{ item }}"
  become: yes
  become_method: sudo
  with_items:
    - trash-cli
    - mc
    - pv
    - bash-completion
    - lib32ncurses5
    - pdfgrep
    - gnome-terminal

- name: Install system tools via APT
  apt:
    name: "{{ item }}"
  become: yes
  become_method: sudo
  with_items:
    - apt-file
    - locate
    - lsof
    - htop
    - moreutils
    - kuser

- name: Install npm via APT
  apt:
    name: npm
  become: yes
  become_method: sudo
  when: npm_is_from_apt

- name: Install other APT packages
  apt:
    name: "{{ item }}"
  become: yes
  become_method: sudo
  with_items:
    - ia32-libs
    - gmrun
    - mcrypt
    - pwgen
    - maven2
    - mongodb
    - mysql-client

- name: "Add source line to bashrc"
  lineinfile:
    dest: "{{ main_bashrc_on_host }}"
    line: "source ${ansibleInventoryDir}/files/bashrc # uuidgen-79cb621e-49f4-4662-bd6c-518e97ae97cb"
    regexp: uuidgen-79cb621e-49f4-4662-bd6c-518e97ae97cb
    insertafter: uuidgen-20ce84f6-6313-4d61-8641-245c42741ffb

- name: "Add workstation to hosts"
  lineinfile:
    dest: /etc/hosts
    line: "10.111.8.108 workstation # uuidgen-4af6b62e-6972-4e3d-a7ab-9f220c6a861d"
    regexp: uuidgen-4af6b62e-6972-4e3d-a7ab-9f220c6a861d
  become: yes
  become_method: sudo
