---
- name: Add APT source for spotify
  apt_repository:
    repo: deb [trusted=yes] http://repository.spotify.com stable non-free
  become: yes
  become_method: sudo

- name: Install APT package
  apt:
    name: spotify-client
  become: yes
  become_method: sudo

- name: Install libudev1 via APT
  apt:
    name: libudev1
  become: yes
  become_method: sudo
