---
- name: Remove deprecated APT source for spotify
  apt_repository:
    repo: deb http://repository.spotify.com precise stable non-free
    state: absent
    update_cache: no
  become: yes
  become_method: sudo

- name: Add APT key for spotify
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: BBEBDCB318AD50EC6865090613B00F1FD2C19886
  become: yes
  become_method: sudo

- name: Add APT source for spotify
  apt_repository:
    repo: deb http://repository.spotify.com stable non-free
  become: yes
  become_method: sudo

- name: Install APT package
  apt:
    name: spotify-client
  become: yes
  become_method: sudo
