---
dependencies:
  - role: add-sudoers
  - role: git-client
  - role: link-documents
  - role: zeal-client

  - role: create-symlink
    link_name: kwriterc
    link_path: "{{ lookup('env', 'HOME') }}/.kde/share/config"
    # Unfortunately we can't use 'role_path'
    # because of https://github.com/ansible/ansible/issues/10374 :
    target: "{{ inventory_dir }}/files/kwriterc"

  - role: create-symlink
    link_name: .bash_profile
    link_path: "{{ lookup('env', 'HOME') }}"
    # Unfortunately we can't use 'role_path'
    # because of https://github.com/ansible/ansible/issues/10374 :
    target: "{{ inventory_dir }}/files/bash_profile"

  - role: create-symlink
    link_name: .bash_aliases
    link_path: "{{ lookup('env', 'HOME') }}"
    # Unfortunately we can't use 'role_path'
    # because of https://github.com/ansible/ansible/issues/10374 :
    target: "{{ inventory_dir }}/files/bash_aliases"

  - role: line-in-file
    dest: "{{ main_bashrc_on_host }}"
    dest_description: bashrc
    # Unfortunately we can't use 'role_path'
    # because of https://github.com/ansible/ansible/issues/10374 :
    line: "ansibleInventoryDir={{ inventory_dir }} # uuidgen-20ce84f6-6313-4d61-8641-245c42741ffb"
    line_description: args
    regexp: uuidgen-20ce84f6-6313-4d61-8641-245c42741ffb

  - role: create-symlink
    link_name: inputrc
    link_path: "/etc"
    # Unfortunately we can't use 'role_path'
    # because of https://github.com/ansible/ansible/issues/10374 :
    target: "{{ inventory_dir }}/files/inputrc"
    with_sudo: yes

  - role: create-symlink
    link_name: config
    link_path: "{{ lookup('env', 'HOME') }}/.ssh"
    # Unfortunately we can't use 'role_path'
    # because of https://github.com/ansible/ansible/issues/10374 :
    target: "{{ inventory_dir }}/files/ssh-config"

  - role: create-symlink
    link_name: .npmrc
    link_path: "{{ lookup('env', 'HOME') }}"
    # Unfortunately we can't use 'role_path'
    # because of https://github.com/ansible/ansible/issues/10374 :
    target: "{{ inventory_dir }}/files/npmrc"

  - role: create-symlink
    link_name: .hgrc
    link_path: "{{ lookup('env', 'HOME') }}"
    # Unfortunately we can't use 'role_path'
    # because of https://github.com/ansible/ansible/issues/10374 :
    target: "{{ inventory_dir }}/files/hgrc"

  - role: create-symlink
    link_name: .pylintrc
    link_path: "{{ lookup('env', 'HOME') }}"
    # Unfortunately we can't use 'role_path'
    # because of https://github.com/ansible/ansible/issues/10374 :
    target: "{{ inventory_dir }}/files/pylintrc"

  - role: create-symlink
    link_name: .vimrc
    link_path: "{{ lookup('env', 'HOME') }}"
    # Unfortunately we can't use 'role_path'
    # because of https://github.com/ansible/ansible/issues/10374 :
    target: "{{ inventory_dir }}/files/vimrc"

  - role: create-symlink
    link_name: .xbindkeysrc.scm
    link_path: "{{ lookup('env', 'HOME') }}"
    # Unfortunately we can't use 'role_path'
    # because of https://github.com/ansible/ansible/issues/10374 :
    target: "{{ inventory_dir }}/files/xbindkeysrc.scm"
