alias e='~/.emacs.d/bin/emacsclient.sh'
alias ee='~/.emacs.d/bin/ee.sh'

alias ls='ls --color'
alias ll='ls -alF'

alias spotify='env LC_NUMERIC=en_US.utf8 spotify'
alias trsh='bash ${ansibleInventoryDir}/files/trash.sh'
alias gitupdate='bash ${ansibleInventoryDir}/files/gitupdate.sh'
alias update='bash ${ansibleInventoryDir}/files/update.sh'
alias homesize='bash ${ansibleInventoryDir}/files/homesize.sh'
alias memtop='atop -pMl'
alias find_forks='python ~/Documents/git/find_forks'

alias dock='xrandr --output HDMI1 --rotate normal --mode 1920x1200 && xrandr --output eDP1 --off'
alias dockAtWork='xrandr --output HDMI1 --rotate normal --mode 1920x1080 && xrandr --output eDP1 --off'
alias undock='xrandr --output eDP1 --mode 1366x768 && xrandr --output HDMI1 --off'
alias night='xrandr --output eDP1 --brightness .4 --gamma .6:.6:.6'
alias day='xrandr --output eDP1 --brightness 1 --gamma 1:1:1'
