HISTSIZE=5000
export TERM=xterm-256color

# set -o vi  # unfortunately deactivates ctrl-l (clear)

export EDITOR="code --wait --reuse-window"

. ~/bin/git-prompt.sh
export GIT_PS1_SHOWDIRTYSTATE=true
export GIT_PS1_SHOWUPSTREAM=auto
export GIT_PS1_SHOWSTASHSTATE=true
export GIT_PS1_SHOWUNTRACKEDFILES=true
export GIT_PS1_HIDE_IF_PWD_IGNORED=true

# Inspired from https://gist.github.com/miki725/9783474
function setPythonVenv {
  if test -z "$VIRTUAL_ENV"; then
    pythonVenv=""
  else
    pythonVenv="${BLUE}(`basename \"$VIRTUAL_ENV\"`)${NOCOLOR} "
  fi
}

# Show python venv, git status and exit status on prompt:
function setBashPrompt {
  exitStatus=$?

  BLUE=$'\033[1;34m'
  GRAY=$'\033[1;30m'
  RED=$'\033[1;31m'
  NOCOLOR=$'\033[m'

  setPythonVenv

  if [ $exitStatus -eq 0 ]; then
    exitStatusColor=$GRAY
  else
    exitStatusColor=$RED
  fi

  PS1='${pythonVenv}\u@\h:\w\[\033[1;32m\]$(__git_ps1 " [%s]")\[\033[0m\]\[$exitStatusColor\][$exitStatus]\[$NOCOLOR\]\$ '
}
PROMPT_COMMAND=setBashPrompt

# https://unix.stackexchange.com/a/1292/36560
# Avoid duplicates
export HISTCONTROL=ignoredups:erasedups
# When the shell exits, append to the history file instead of overwriting it
shopt -s histappend
# After each command, append to the history file
export PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND$'\n'}history -a"

# User-specific commands:
export PATH="~/bin:~/Documents/git/bin:${PATH}"

export PATH="~/go/bin:${PATH}"

# See https://super-unix.com/ubuntu/ubuntu-how-to-set-up-ccache/
export PATH="/usr/lib/ccache:${PATH}"
