alias e='~/.emacs.d/bin/emacsclient.sh'
alias ee='~/.emacs.d/bin/ee.sh'

alias ls='ls --color'
alias ll='ls -alF'

alias spotify='env LC_NUMERIC=en_US.utf8 spotify'
alias trsh='bash ${ansibleInventoryDir}/files/trash.sh'
alias gitupdate='bash ${ansibleInventoryDir}/files/gitupdate.sh'
alias homesize='bash ${ansibleInventoryDir}/files/homesize.sh'
alias memtop='atop -pMl'
alias find_forks='python ~/Documents/git/find_forks'
