# args:
#   ansibleInventoryDir

HISTSIZE=5000
export TERM=xterm-256color

# set -o vi  # unfortunately deactivates ctrl-l (clear)

alias e='~/.emacs.d/bin/emacsclient.sh'
alias ee='~/.emacs.d/bin/ee.sh'
export EDITOR=~/.emacs.d/bin/emacsclient.sh

alias ls='ls --color'
alias ll='ls -alF'

alias spotify='env LC_NUMERIC=en_US.utf8 spotify'
alias trsh='bash ${ansibleInventoryDir}/files/trash.sh'
alias gitupdate='bash ${ansibleInventoryDir}/files/gitupdate.sh'
alias update='bash ${ansibleInventoryDir}/files/update.sh'
alias homesize='bash ${ansibleInventoryDir}/files/homesize.sh'
alias find_forks='python ~/Documents/git/find_forks'

alias cat=bat # https://github.com/sharkdp/bat

alias dock='xrandr --output HDMI1 --rotate normal --mode 1920x1200 && xrandr --output eDP1 --off'
alias dockAtWork='xrandr --output HDMI1 --rotate normal --mode 1920x1080 && xrandr --output eDP1 --off'
alias undock='xrandr --output eDP1 --mode 1366x768 && xrandr --output HDMI1 --off'
alias night='xrandr --output eDP1 --brightness .4 --gamma .6:.6:.6'
alias day='xrandr --output eDP1 --brightness 1 --gamma 1:1:1'

. ~/bin/git-prompt.sh
export GIT_PS1_SHOWDIRTYSTATE=true
export GIT_PS1_SHOWUPSTREAM=auto
export GIT_PS1_SHOWSTASHSTATE=true
export GIT_PS1_SHOWUNTRACKEDFILES=true
export GIT_PS1_HIDE_IF_PWD_IGNORED=true

# Show git status and exit status on prompt:
function setBashPrompt {
  exitStatus=$?

  GRAY=$'\033[1;30m'
  RED=$'\033[1;31m'
  NOCOLOR=$'\033[m'

  if [ $exitStatus -eq 0 ]; then
    exitStatusColor=$GRAY
  else
    exitStatusColor=$RED
  fi

  PS1='\u@\h:\w\[\033[1;32m\]$(__git_ps1 " [%s]")\[\033[0m\]\[$exitStatusColor\][$exitStatus]\[$NOCOLOR\]\$ '
}
PROMPT_COMMAND=setBashPrompt

# Solves emacs accent bug:
# https://bugs.launchpad.net/emacs-snapshot/+bug/1251176
export XMODIFIERS=''

# User-specific commands:
export PATH="~/bin:${PATH}"

export GOROOT=~/bin/go
export GOPATH=~/gocode
export PATH=$GOROOT/bin:$PATH
export PATH=$GOPATH/bin:$PATH
