---
dependencies:
  - role: add-sudoers

  - role: create-symlink
    link_name: start_icon.png
    link_path: "/opt/configurelinux"
    # Unfortunately we can't use 'role_path'
    # because of https://github.com/ansible/ansible/issues/10374 :
    target: "{{ inventory_dir }}/files/start_icon.png"
    with_sudo: yes

  - role: create-symlink
    link_name: autostart.desktop
    link_path: "{{ lookup('env', 'HOME') }}/.config/autostart"
    # Unfortunately we can't use 'role_path'
    # because of https://github.com/ansible/ansible/issues/10374 :
    target: "{{ inventory_dir }}/files/autostart.desktop"

  - role: create-symlink
    link_name: logind.conf
    link_path: /etc/systemd
    # Unfortunately we can't use 'role_path'
    # because of https://github.com/ansible/ansible/issues/10374 :
    target: "{{ inventory_dir }}/files/logind.conf"
    with_sudo: yes

  - role: create-symlink
    link_name: locale
    link_path: /etc/default
    # Unfortunately we can't use 'role_path'
    # because of https://github.com/ansible/ansible/issues/10374 :
    target: "{{ inventory_dir }}/files/locale"
    with_sudo: yes

  - role: create-symlink
    link_name: autostart.sh
    # See autostart.desktop why we can't put this file in ~/bin :
    link_path: /usr/local/bin
    # Unfortunately we can't use 'role_path'
    # because of https://github.com/ansible/ansible/issues/10374 :
    target: "{{ inventory_dir }}/files/autostart.sh"
    with_sudo: yes

  - role: create-symlink
    link_name: purgetrash.sh
    link_path: "{{ lookup('env', 'HOME') }}/bin"
    # Unfortunately we can't use 'role_path'
    # because of https://github.com/ansible/ansible/issues/10374 :
    target: "{{ inventory_dir }}/files/purgetrash.sh"
    with_sudo: yes

  - role: create-symlink
    link_name: deskopen.sh
    link_path: "{{ lookup('env', 'HOME') }}/bin"
    # Unfortunately we can't use 'role_path'
    # because of https://github.com/ansible/ansible/issues/10374 :
    target: "{{ inventory_dir }}/files/deskopen.sh"

  - role: create-symlink
    link_name: mount_encrypted_sdcard.sh
    link_path: "{{ lookup('env', 'HOME') }}/bin"
    # Unfortunately we can't use 'role_path'
    # because of https://github.com/ansible/ansible/issues/10374 :
    target: "{{ inventory_dir }}/files/mount_encrypted_sdcard.sh"
    with_sudo: yes
