---
- name: Add APT key for zeal
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 786285426B130F8C8C67CEF87F73D5BEFC1B6133
  become: yes
  become_method: sudo

- name: Add APT source for zeal
  apt_repository:
    repo: deb http://ppa.launchpad.net/zeal-developers/ppa/ubuntu trusty main
  become: yes
  become_method: sudo

- name: Install APT package
  apt:
    name: zeal
  become: yes
  become_method: sudo

- name: Deploy Zeal.conf
  template:
    src: "{{ role_path }}/files/Zeal.conf"
    dest: "{{ lookup('env', 'HOME') }}/.config/Zeal/Zeal.conf"

- name: Cleanup older Zeal.conf backup
  file:
    path: "{{ lookup('env', 'HOME') }}/.config/Zeal/Zeal.conf.old"
    state: absent
